import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { logger } from '../utils/logger.js';

/** All known text keys used in the bot */
export type TextKey =
  | 'MAIN_MENU'
  | 'BTN_ABOUT'
  | 'BTN_SUBSCRIPTION'
  | 'BTN_SUBSCRIPTION_INLINE'
  | 'BTN_PARTNER'
  | 'BTN_MY_SUBSCRIPTION'
  | 'NO_SUBSCRIPTION'
  | 'BTN_HORMONES'
  | 'BTN_ACCOUNT'
  | 'ACCOUNT_ADD_EMAIL'
  | 'ACCOUNT_EMAIL_PROMPT'
  | 'ACCOUNT_EMAIL_SAVED'
  | 'ACCOUNT_EMAIL_INVALID'
  | 'BTN_SUPPORT'
  | 'SUPPORT'
  | 'TARIFF_TITLE'
  | 'TARIFF_DETAIL_1M'
  | 'TARIFF_DETAIL_6M'
  | 'TARIFF_DETAIL_12M'
  | 'PAYMENT_METHOD_TITLE'
  | 'BTN_PAY_CARD'
  | 'BTN_PAY_USDT'
  | 'BTN_BACK_TARIFFS'
  | 'BTN_USDT_PAID'
  | 'BTN_USDT_CANCEL'
  | 'BTN_HOME'
  | 'BTN_BACK'
  | 'ABOUT'
  | 'INVITE_MESSAGE'
  | 'BTN_INVITE_CLUB'
  | 'BTN_INVITE_LIBRARY'
  | 'BTN_INVITE_CHATS'
  // Subscription flow
  | 'ALREADY_SUBSCRIBED'
  | 'PENDING_CARD_PAYMENT'
  | 'PENDING_CRYPTO_PAYMENT'
  | 'PAYMENT_UNAVAILABLE'
  | 'PAYMENT_LINK_VALIDITY'
  | 'BTN_PAY'
  | 'BTN_CANCEL'
  | 'PAYMENT_CREATION_ERROR'
  | 'PAYMENT_CANCELLED'
  | 'BTN_CHOOSE_TARIFF'
  | 'SUBSCRIPTION_NOT_FOUND'
  | 'PLAN_DETERMINATION_ERROR'
  | 'PAYMENT_ALREADY_PROCESSING'
  | 'PAYMENT_PROCESSING_DOTS'
  | 'BTN_CHECK_SUBSCRIPTION'
  | 'BTN_SUBSCRIBE'
  | 'BTN_RETRY'
  | 'CANCELLED_SUB_INFO'
  | 'BTN_REACTIVATE'
  // Rules
  | 'RULES_TEXT'
  | 'BTN_ACCEPT_RULES'
  // Navigation
  | 'UNHANDLED_MESSAGE'
  // Account
  | 'ACCOUNT_TITLE'
  | 'ACCOUNT_SUBSCRIPTION_ACTIVE'
  | 'ACCOUNT_SUBSCRIPTION_CANCELLED'
  | 'ACCOUNT_SUBSCRIPTION_NONE'
  | 'ACCOUNT_NOT_SET'
  | 'ACCOUNT_EMAIL_FORM_TITLE'
  | 'ACCOUNT_EMAIL_FORM_INSTRUCTION'
  | 'ACCOUNT_EMAIL_SAVED_INLINE'
  | 'ACCOUNT_EMAIL_INVALID_INLINE'
  | 'BTN_CHANGE_EMAIL'
  | 'BTN_ADD_EMAIL'
  | 'BTN_CANCEL_EMAIL'
  // My subscription
  | 'BTN_MY_CLUB_LINKS'
  | 'BTN_MANAGE_SUBSCRIPTION'
  | 'BTN_CHANGE_PLAN'
  | 'BTN_CHANGE_METHOD'
  | 'BTN_CHANGE_CARD'
  | 'BTN_CANCEL_SUBSCRIPTION'
  | 'BTN_YES_CANCEL'
  | 'BTN_NO_GO_BACK'
  | 'BTN_MY_SUB_INLINE'
  | 'CANCEL_SUBSCRIPTION_CONFIRM'
  | 'SUBSCRIPTION_NOT_FOUND_OR_CANCELLED'
  | 'SUBSCRIPTION_NOT_FOUND_OR_EXPIRED'
  | 'CHANGE_PLAN_ERROR'
  | 'CHANGE_METHOD_ERROR'
  | 'METHOD_CHANGED_TO_CRYPTO'
  | 'CHANGE_CARD_CRYPTO_ONLY'
  | 'CHANGE_CARD_UNAVAILABLE'
  | 'CHANGE_METHOD_UNAVAILABLE'
  | 'BTN_SWITCH_TO_USDT'
  | 'BTN_ADD_CARD'
  | 'BTN_ADD_NEW_CARD'
  | 'BTN_CANCEL_CARD_CHANGE'
  | 'BTN_CANCEL_METHOD_CHANGE'
  | 'SUBSCRIPTION_REACTIVATED'
  // Webhook / payment results
  | 'CARD_CHANGED_SUCCESS'
  | 'CARD_SAVE_ERROR'
  | 'METHOD_CHANGED_TO_CARD'
  | 'METHOD_CHANGE_FAILED'
  | 'CARD_ADD_FAILED'
  | 'METHOD_CHANGE_DECLINED'
  // Jobs
  | 'AUTO_RENEWAL_PLAN_ERROR'
  | 'BTN_PAY_NOW'
  | 'SUBSCRIPTION_EXPIRED_NOTIFICATION'
  // Partner
  | 'PARTNER_SUBSCRIPTION_REQUIRED'
  | 'WITHDRAW_DATE_RESTRICTION'
  | 'WITHDRAW_INSUFFICIENT_FUNDS_UAH'
  | 'WITHDRAW_REQUEST_CREATED'
  | 'WITHDRAW_APPROVED'
  | 'WITHDRAW_REJECTED'
  | 'BTN_WITHDRAW_UAH'
  | 'BTN_WITHDRAW_USDT'
  | 'BTN_CONFIRM_WITHDRAWAL'
  | 'BTN_SHARE_REFERRAL'
  | 'BTN_MY_REFERRAL_LINK'
  | 'BTN_MY_REFERRALS'
  | 'BTN_BALANCE'
  | 'BTN_STATS'
  | 'BTN_DOWNLOAD_REFERRALS'
  | 'PARTNER_NO_REFERRALS'
  | 'PARTNER_CONTENT_CHANNEL'
  // USDT payment
  | 'USDT_PAYMENT_UNAVAILABLE'
  | 'USDT_PENDING_CARD'
  | 'CRYPTO_PAYMENT_UNDER_REVIEW'
  | 'CRYPTO_NO_ACTIVE_PAYMENT'
  | 'CRYPTO_ENTER_HASH'
  | 'CRYPTO_PAYMENT_CANCELLED'
  | 'CRYPTO_HASH_SUBMITTED'
  | 'CRYPTO_VERIFICATION_ERROR'
  | 'CRYPTO_PAYMENT_DENIED'
  | 'BTN_HASH_INSTRUCTION'
  | 'BTN_TOP_UP_INSTRUCTION'
  | 'BTN_HOW_TO_PAY'
  | 'CONTINUE_PROMPT'
  // USDT admin
  | 'PAYMENT_NOT_FOUND'
  | 'PAYMENT_ALREADY_PROCESSED'
  | 'BTN_SUPPORT_CONTACT'
  // Success page
  | 'SUCCESS_PAGE_TITLE'
  | 'SUCCESS_PAGE_MESSAGE'
  | 'PROCESSING_PAGE_TITLE'
  | 'PROCESSING_PAGE_MESSAGE'
  // Dynamic templates
  | 'MY_SUB_ACTIVE'
  | 'MY_SUB_CANCELLED'
  | 'SUB_CANCELLED_NOTIFICATION'
  | 'PLAN_CHANGED_SUCCESS'
  | 'METHOD_CARD_TO_CRYPTO'
  | 'METHOD_CRYPTO_TO_CARD'
  | 'ADD_CARD_INVOICE'
  | 'CHANGE_CARD_TEXT'
  | 'CHANGE_CARD_INVOICE'
  | 'METHOD_LABEL_CARD'
  | 'METHOD_LABEL_USDT'
  | 'PARTNER_STATS'
  | 'PARTNER_BALANCE'
  | 'PARTNER_BALANCE_PENDING'
  | 'WITHDRAW_INSUFFICIENT'
  | 'WITHDRAW_CONFIRM'
  | 'PARTNER_REFERRALS_LIST'
  | 'PARTNER_REFERRAL_LINK'
  | 'PAYMENT_SUCCESS_RENEWAL'
  | 'PAYMENT_SUCCESS_ACTIVATION'
  | 'PAYMENT_SUCCESS_TEMPLATE'
  | 'PAYMENT_DECLINED_TEMPLATE'
  | 'CHARGE_FAILED_TEMPLATE'
  | 'RETRY_FAILED_TEMPLATE'
  | 'ACCOUNT_INFO'
  | 'PARTNER_MENU_TEXT'
  | 'COMMISSION_DISABLED'
  | 'PARTNER_COMMISSION_FIRST'
  | 'PARTNER_COMMISSION_RECURRING'
  | 'USDT_PAYMENT_INSTRUCTIONS'
  | 'USDT_HOW_TO_PAY'
  | 'CHANGE_PLAN_CURRENT'
  | 'CHANGE_PLAN_OTHER'
  | 'AVAILABLE_PLANS'
  | 'PLAN_CHANGE_EFFECTIVE'
  | 'CARD_NOT_SAVED'
  | 'BTN_CHANGE_CONFIRM'
  | 'BTN_SUBSCRIBE_PARTNER'
  | 'WITHDRAWAL_ALREADY_PROCESSED'
  | 'BTN_QUESTION'
  | 'BTN_WRITE_SUPPORT'
  | 'BTN_WRITE_SUPPORT_PARTNER'
  | 'WITHDRAWAL_CREATE_ERROR'
  | 'DATA_LOAD_ERROR'
  | 'CONFIG_ERROR'
  | 'SHARE__REFFERALS_TEXT'
  | 'PAYMENT_PAGE_HTML_TITLE'
  | 'CARD_LABEL'
  | 'DURATION_1M'
  | 'DURATION_6M'
  | 'DURATION_12M'
  | 'CRYPTO_RENEWAL_REMINDER'
  | 'BTN_PAY_USDT_INLINE'
  | 'USERNAME_NONE'
  | 'CARD_PAN_SAVED'
  | 'UNKNOWN_ERROR'
  | 'PAYMENT_INVOICE_TEMPLATE'
  | 'USDT_HASH_INSTRUCTION_URL'
  | 'USDT_TOP_UP_INSTRUCTION_URL'
;

/**
 * Path to texts.json — resolved from project root (process.cwd()),
 * not from __dirname, so it works both in dev (tsx src/) and
 * production (node dist/) without copying JSON to dist/.
 */
const TEXTS_PATH = join(process.cwd(), 'src', 'texts', 'texts.json');

/** In-memory cache — loaded once at startup, reloaded manually via reloadTexts() */
let cache: Record<TextKey, string> = JSON.parse(
  readFileSync(TEXTS_PATH, 'utf-8'),
);

/**
 * All bot texts. Read from in-memory cache (0ms).
 * Call reloadTexts() to pick up changes from texts.json.
 */
export const TEXTS: Record<TextKey, string> = new Proxy({} as Record<TextKey, string>, {
  get(_target, prop: string) {
    return cache[prop as TextKey];
  },
});

/**
 * Reload texts from texts.json into memory.
 * Called from webhook server when admin clicks "Apply changes".
 */
export function reloadTexts(): void {
  try {
    cache = JSON.parse(readFileSync(TEXTS_PATH, 'utf-8'));
    logger.info('Texts reloaded from file');
  } catch (err) {
    logger.error('Failed to reload texts.json', err);
    throw err;
  }
}
